name: DBT_SNOWFLAKE        # Change this to your project name
version: 1.0.0
config-version: 2

# This should match the profile name in dbt Cloud connection settings
profile: Snowflake

model-paths: ["models"]           # Folder where your models are stored
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

# Optional: global configs
target-path: "target"             # Where compiled SQL is stored
clean-targets: ["target", "dbt_modules"]

models:
  DBT_SNOWFLAKE:           # Must match the "name" at top
    +materialized: view           # Default materialization for models
    staging:
      +materialized: view
    marts:
      +materialized: table
